### ISSUE TITLE
js里自动添加到head里的样式少了个%

### ISSUE THREAD

**Issue by shiiiiiiji** [yuanzm/preventoverscrolljs#10]
```css
<style id="prevent_over_scroll_style">
.prevent_over_scroll_container{
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch;
} 
html, body {
  width: 100%; 
  height: 100;  /* 这里少了个% */
}
</style>
```
